// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv_WHSylw7UgFNL_cfTI9-PYZ0u8i5INQ',
    appId: '1:510614945522:android:ad57612ce1287519c65a6b',
    messagingSenderId: '510614945522',
    projectId: 'jobway-project',
    storageBucket: 'jobway-project.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyLKvIiZLoL4SnCnaLvPnNwco4GUV4CCo',
    appId: '1:510614945522:ios:cca22a4df966cb7dc65a6b',
    messagingSenderId: '510614945522',
    projectId: 'jobway-project',
    storageBucket: 'jobway-project.firebasestorage.app',
    iosBundleId: 'com.example.jobwayApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClBtq__Bip2gmhCjhUpjIgLRDaZj3ZW8o',
    appId: '1:510614945522:web:8a65bcdf2b5865c0c65a6b',
    messagingSenderId: '510614945522',
    projectId: 'jobway-project',
    authDomain: 'jobway-project.firebaseapp.com',
    storageBucket: 'jobway-project.firebasestorage.app',
    measurementId: 'G-N3C6ZDWW87',
  );
}
